/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sales_and_inventory;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Fernyl Jean
 * 
 * 
 * 
 *
 */





public class settings extends javax.swing.JPanel {
  
     private static final String username="root";
     private static final String password="";
     private static final String dataConn="jdbc:mysql://localhost:3306/sales and inventory management";
   
     Connection sqlConn= null;
     PreparedStatement pst= null;
     ResultSet rs = null;
    public settings() {
        initComponents();
         displayTF();
        
         this.setBounds(0,0,1393, 895);
        this.setVisible(true);
        this.setLayout(new CardLayout());
        
    }
    
    
    
    private void displayTF(){
    
     try{
       try{
       
        Class.forName("com.mysql.cj.jdbc.Driver");
       
       } catch (ClassNotFoundException ex) {
             Logger.getLogger(settings.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        sqlConn=DriverManager.getConnection(dataConn,username,password);
        pst = sqlConn.prepareStatement("SELECT username_login,password_login FROM login");
         rs= pst.executeQuery();
        
          if (rs.next()){
          
          
          usernameTF.setText(rs.getString("username_login"));
          passwordTF.setText(rs.getString("password_login"));
        
          
           // rs.close();
            pst.close();
            sqlConn.close();    
          
          }
            
           
      }
      
      catch (SQLException ex){
       
        Logger.getLogger(settings.class.getName()).log(Level.SEVERE, null, ex);
      }
    
    
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel(25);
        passwordTF = new javax.swing.JTextField();
        usernameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        setBtn = new javax.swing.JButton();
        jPanel3 =  new RoundedPanel(25);
        delete_prodmngr = new javax.swing.JButton();
        delete_saleT = new javax.swing.JButton();
        delete_purchaseT = new javax.swing.JButton();
        jPanel4 =  new RoundedPanel(25);
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        jLabel1.setBackground(new java.awt.Color(4, 77, 69));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 77, 69));
        jLabel1.setText("SETTINGS");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 77, 69));
        jLabel2.setText("PRIVACY");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 77, 69));
        jLabel3.setText("DATA");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(4, 77, 69));
        jLabel4.setText("ABOUT");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        passwordTF.setBackground(new java.awt.Color(255, 255, 255));
        passwordTF.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        passwordTF.setForeground(new java.awt.Color(51, 70, 112));

        usernameTF.setBackground(new java.awt.Color(255, 255, 255));
        usernameTF.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(51, 70, 112));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 77, 69));
        jLabel5.setText("NEW USERNAME");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 77, 69));
        jLabel6.setText("NEW PASSWORD");

        setBtn.setBackground(new java.awt.Color(20, 166, 151));
        setBtn.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        setBtn.setForeground(new java.awt.Color(255, 255, 255));
        setBtn.setText("SET");
        setBtn.setBorderPainted(false);
        setBtn.setFocusPainted(false);
        setBtn.setFocusable(false);
        setBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(setBtn)
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);

        delete_prodmngr.setBackground(new java.awt.Color(255, 255, 255));
        delete_prodmngr.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        delete_prodmngr.setForeground(new java.awt.Color(4, 77, 69));
        delete_prodmngr.setText("DELETE PRODUCT MANAGER ");
        delete_prodmngr.setBorderPainted(false);
        delete_prodmngr.setFocusable(false);
        delete_prodmngr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        delete_prodmngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_prodmngrActionPerformed(evt);
            }
        });

        delete_saleT.setBackground(new java.awt.Color(255, 255, 255));
        delete_saleT.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        delete_saleT.setForeground(new java.awt.Color(4, 77, 69));
        delete_saleT.setText("DELETE SALE TRANSACTIONS");
        delete_saleT.setBorderPainted(false);
        delete_saleT.setFocusable(false);
        delete_saleT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        delete_saleT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_saleTActionPerformed(evt);
            }
        });

        delete_purchaseT.setBackground(new java.awt.Color(255, 255, 255));
        delete_purchaseT.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        delete_purchaseT.setForeground(new java.awt.Color(4, 77, 69));
        delete_purchaseT.setText("DELETE PURCHASE TRANSACTIONS");
        delete_purchaseT.setBorderPainted(false);
        delete_purchaseT.setFocusable(false);
        delete_purchaseT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        delete_purchaseT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_purchaseTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_prodmngr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_saleT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_purchaseT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(delete_prodmngr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_saleT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_purchaseT)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(4, 77, 69));
        jButton3.setText("ABOUT THIS SYSTEM");
        jButton3.setBorderPainted(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(152, 261, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBtnActionPerformed
      try{
       try{
       
        Class.forName("com.mysql.cj.jdbc.Driver");
       
       } catch (ClassNotFoundException ex) {
             Logger.getLogger(settings.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        sqlConn=DriverManager.getConnection(dataConn,username,password);
        pst = sqlConn.prepareStatement("UPDATE login SET username_login=?,password_login=?");
        
          pst.setString(1 , usernameTF.getText());
          pst.setString(2 , passwordTF.getText());
          
            pst.executeUpdate();
            
             
            JLabel label = new JLabel(" Username and Password updated successfully.");
            label.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            JOptionPane.showMessageDialog(this, label);
            
            //rs.close();
            pst.close();
            sqlConn.close();  
           
      }
      
      catch (SQLException ex){
       
        Logger.getLogger(settings.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_setBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      aboutPage a = new aboutPage();
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void delete_saleTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_saleTActionPerformed
        try {
          
          Class.forName("com.mysql.cj.jdbc.Driver");
          sqlConn=DriverManager.getConnection(dataConn,username,password);
          
           JLabel label2 = new JLabel("Are you sure you want to delete all the data from Sale Transaction?");
        
           
            label2.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            
            int deleteItem =  JOptionPane.showConfirmDialog(null, label2, "WARNING!",JOptionPane.YES_NO_OPTION);
            ///////
            if (deleteItem==JOptionPane.YES_OPTION){
                
                
            JLabel label3 = new JLabel("This process cannot be undone. Continue?");       
            label3.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            
            int deleteItem1 =  JOptionPane.showConfirmDialog(null, label3, "WARNING!",JOptionPane.YES_NO_OPTION);
                ////////
            if (deleteItem1==JOptionPane.YES_OPTION){
            
            sqlConn=DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("DELETE sale_transaction FROM sale_transaction");
              
             pst.executeUpdate();
              
            JLabel label1 = new JLabel("Sale Transaction updated successfully.");
            label1.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            JOptionPane.showMessageDialog(null,label1,"", JOptionPane.OK_OPTION);
            
            
            
            }
         
            }
            
            rs.close();
            pst.close();
            sqlConn.close();  
          
         
          
      } catch(SQLException | ClassNotFoundException ex){
      }
    }//GEN-LAST:event_delete_saleTActionPerformed

    private void delete_prodmngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_prodmngrActionPerformed
       try {
          
          Class.forName("com.mysql.cj.jdbc.Driver");
          sqlConn=DriverManager.getConnection(dataConn,username,password);
          
           JLabel label2 = new JLabel("Are you sure you want to delete all the data from Product Manager?");
        
           
            label2.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            
            int deleteItem =  JOptionPane.showConfirmDialog(null, label2, "WARNING!",JOptionPane.YES_NO_OPTION);
            ///////
            if (deleteItem==JOptionPane.YES_OPTION){
                
                
            JLabel label3 = new JLabel("This process cannot be undone. Continue?");       
            label3.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            
            int deleteItem1 =  JOptionPane.showConfirmDialog(null, label3, "WARNING!",JOptionPane.YES_NO_OPTION);
                ////////
            if (deleteItem1==JOptionPane.YES_OPTION){
            
            sqlConn=DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("DELETE prod_manager FROM prod_manager");
              
             pst.executeUpdate();
              
            JLabel label1 = new JLabel(" Product Manager updated successfully.");
            label1.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            JOptionPane.showMessageDialog(null,label1,"", JOptionPane.OK_OPTION);
            
            
            
            }
         
            }
            
            rs.close();
            pst.close();
            sqlConn.close();  
          
         
          
      } catch(SQLException | ClassNotFoundException ex){
      }
    }//GEN-LAST:event_delete_prodmngrActionPerformed

    private void delete_purchaseTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_purchaseTActionPerformed
       try {
          
          Class.forName("com.mysql.cj.jdbc.Driver");
          sqlConn=DriverManager.getConnection(dataConn,username,password);
          
           JLabel label2 = new JLabel("Are you sure you want to delete all the data from Purchase Transaction?");
        
           
            label2.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            
            int deleteItem =  JOptionPane.showConfirmDialog(null, label2, "WARNING!",JOptionPane.YES_NO_OPTION);
            ///////
            if (deleteItem==JOptionPane.YES_OPTION){
                
                
            JLabel label3 = new JLabel("This process cannot be undone. Continue?");       
            label3.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            
            int deleteItem1 =  JOptionPane.showConfirmDialog(null, label3, "WARNING!",JOptionPane.YES_NO_OPTION);
                ////////
            if (deleteItem1==JOptionPane.YES_OPTION){
            
            sqlConn=DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("DELETE purchase_transaction FROM purchase_transaction");
              
             pst.executeUpdate();
              
            JLabel label1 = new JLabel("Purchase Transaction updated successfully.");
            label1.setFont(new Font("Yu Gothic UI", Font.BOLD, 12));
            JOptionPane.showMessageDialog(null,label1,"", JOptionPane.OK_OPTION);
            
            
            
            }
         
            }
            
            rs.close();
            pst.close();
            sqlConn.close();  
          
         
          
      } catch(SQLException | ClassNotFoundException ex){
      }
    }//GEN-LAST:event_delete_purchaseTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_prodmngr;
    private javax.swing.JButton delete_purchaseT;
    private javax.swing.JButton delete_saleT;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JButton setBtn;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables


   class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }







}
